function coefficientsflightdata = importfile_coeff(filename, dataLines)
%IMPORTFILE Import data from a text file
%  COEFFICIENTSFLIGHTDATA = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  COEFFICIENTSFLIGHTDATA = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  coefficientsflightdata = importfile("C:\Users\kevin\OneDrive - UPV\auto-rocketpy\coefficients_flight_data.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Mar-2025 12:15:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["t", "x", "y", "z", "vx", "vy", "vz", "w1", "w2", "w3", "R1", "R2", "R3", "M1", "M2", "M3", "status"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "status", "EmptyFieldRule", "auto");

% Import the data
coefficientsflightdata = readtable(filename, opts);

end